{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nycflights13
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nycflights13_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nycflights13/nycflights13_{{ version }}.tar.gz
  sha256: 0e87c5a4e285f16750e91c75aeba33b1e4682cdabf4a3effe5a1de7398394a1d

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-tibble
  run:
    - r-base
    - r-tibble

test:
  commands:
    - $R -e "library('nycflights13')"           # [not win]
    - "\"%R%\" -e \"library('nycflights13')\""  # [win]

about:
  home: http://github.com/hadley/nycflights13
  license: CC0-1.0
  summary: Airline on-time data for all flights departing NYC in 2013.  Also includes useful 'metadata' on airlines, airports, weather, and planes.
  license_family: CC
  license_file:
    - LICENSE-CC0

extra:
  recipe-maintainers:
    - conda-forge/r
