{% set version = "1.0.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nycflights13
  version: {{ version|replace("-", "_") }}

source:
  fn: nycflights13_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/nycflights13_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/nycflights13/nycflights13_{{ version }}.tar.gz
  sha256: 1626cae2329e23343fe797553c5a2af341cf7abe31d3545ca45bfb783b2b6081

build:
  noarch: generic
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-tibble

  run:
    - r-base
    - r-tibble

test:
  commands:
    - $R -e "library('nycflights13')"  # [not win]
    - "\"%R%\" -e \"library('nycflights13')\""  # [win]

about:
  home: http://github.com/hadley/nycflights13
  license: CC0
  summary: Airline on-time data for all flights departing NYC in 2013. Also includes useful 'metadata'
    on airlines, airports, weather, and planes.
  license_family: OTHER

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
