appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mtPS/F4S4+WFv3r9czk6j34o6vyaVQz8xzh/SF6Cf/zGMQWRDnLb4gPWn2QjZvqRmQrGdNeoXoQLrMj4RFQ5wU2RjXytaYzubp2Q1wrdv4xeYV1/gzAhNBY0JB5ytj8Ni4dWYFvGlyp7CTLIpP1p6ObQvZs7iN9Aa7uNFHZUin1eOMfEbJBtvzLEBfNLbpo6hl80+w46QyCoNHTegGdF35B/WhZOU4NEwiTnQgYIHAwlV0omPZLK8lI1Vw3K6pZs2VEAB6wN1uKGDKtfg+Ku0xqK+RSsvcEZeMeiig746ciAOIlUW3cgR874ht8uVSouzv85W0oLaIZwq3UNtrDH+nfXCTnI2x6kHIFLF66Q1/79zbzsrfiolEOADabqQ23G9lZd2eH4G47apAWb2bBkQCq5btpP5bAEDL19A8D4Yeh9JIsPJQdUzyKOl4SgbqGcvsCe8+S595G3a9RqWZCB1BVvX0INfaTT0ngkIaJ8YpHxYLlch130GxwB24PRq44rEpxQI5vpFVRBGIrB5DF7vFaeHn9WDK+HdldAWFowQ3nOjImoOliEq4+mNQlaaohg29TtLzZswOt7Go4ygLsM89VeWfKHUocmIfqtC677HC+TPQa17DcaRe8DYQirztW1R+m1GouT/MeB6S/SBi+4caBL9dYxhKi4jvp4/p3RVps=}
